#!/bin/bash
# KHr
# Periodically test a VPN connection and reconnect if needed.
# Use for VPN servers behind dynamic DNS with periodically changing IP address.


# Path to the current directory where this script is located
DIR=$(dirname $BASH_SOURCE)

# Include common configuration file
source "$DIR/lib/common.sh"


LOG_PREFIX="vpn-watchdog"


# Info log messages
function infoLog {
  _infoLog "$1" "$LOG_PREFIX" "" "ed"
}

# Warning log messages
function warningLog {
  _warningLog "$1" "$LOG_PREFIX" "" "ed"
}

# Error log messages
function errorLog {
  _errorLog "$1" "$LOG_PREFIX" "" "ed"
}


# Check remote host connectivity via ping
result=$(/sbin/ping -c 4 "$CFG_VPN_PING_IP" 2>&1)
rv=$?
echo "$result"
if [[ $rv -ne 0 ]]; then
  /usr/sbin/networksetup -disconnectpppoeservice "$CFG_VPN_NAME"
  sleep 5
  /usr/sbin/networksetup -connectpppoeservice "$CFG_VPN_NAME"
  infoLog "VPN reconnected"
else
  echo  "Successfully pinged '$CFG_VPN_PING_IP'"
fi





