#!/bin/bash
# KHr
# Disconnect from a VPN server

# Path to the current directory where this script is located
DIR=$(dirname $BASH_SOURCE)

# Include common configuration file
source "$DIR/lib/common.sh"


/usr/sbin/networksetup -disconnectpppoeservice "$CFG_VPN_NAME"


